// quiz/src/components/question-list.svelte
<template>
  <QuestionForm on:submit={e => questions.add(e.detail)}></QuestionForm>
  {#each $questions as question, i (question)}
    <div class="box">
      <button class="erase" on:click={e => questions.remove(i)}>X</button>
      <Question statement={question.statement} options={question.options}>
      </Question>
    </div>
  {/each}
</template>

<script lang="ts">
import Question from './question.svelte'
import QuestionForm from './question-form.svelte'
import { questions, type QuestionType } from '../store/questions.store'
</script>

<style>
.box {
  padding: 10px;
  border: 1px solid #aaf;
  border-radius: 5px;
  margin: 10px;
}
.erase {
  float: right;
  z-index: 2;
}
</style>

// quiz/src/components/QuestionList.vue
<template>
  <QuestionForm @on-submit="addQuestion($event)"></QuestionForm>
  <div class="box" v-for="question, i in questionStore.questions">
    <button class="erase" @click="deleteQuestion(i)">X</button>
    <Question
      :statement="question.statement"
      :options="question.options"
    >
    </Question>
  </div>
</template>

<script setup lang="ts">
import Question from './Question.vue'
import QuestionForm from './QuestionForm.vue'
import { questionStore, type QuestionType } from '../store/question.store'

function addQuestion(question: QuestionType) {
  questionStore.add(question)
}

function deleteQuestion(index: number) {
  questionStore.delete(index)
}

</script>

<style>
.box {
  padding: 10px;
  border: 1px solid #aaf;
  border-radius: 5px;
  margin: 10px;
}
.erase {
  float: right;
  z-index: 2;
}
</style>
