// quiz/src/components/results.svelte
{#each answers as answer, i}
  <div class="questionResult">
    <h3>Questão { i + 1 }</h3>
    { answer.statement }: { answer.answer }
  </div>
{/each}

<script>
  export let answers
</script>

<style>
  .questionResult + .questionResult {
    margin-top: 10px;
  }
  h3 {
    margin: 0;
  }
</style>

// quiz/src/components/Results.tsx
import './Results.css'

interface ResultsProps {
  statements: string[]
  answers: string[]
}

export function Results(props: ResultsProps) {
  const results = props.answers.map((answer, index) => (
    <div className="questionResult">
      <h3>Questão { index + 1 }</h3>
      { props.statements[index] }: { answer }
    </div>
  ))
  return <div>{ results }</div>
}
